name: Discord Message Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Discord Message Notify
        run: curl -X POST -F content="${{ github.actor }}が${{github.event_name}}"しました！！関東勝ちましょう△△ https://discord.com/api/webhooks/1325495356678733954/0VMcWQ3rDsKESHLK8NDJ46aghPigyWfRhEocURX1ySlMPE3VEO2nQYIR6AtiXAxNDXVB